version: '3.8'

services:
  habit-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Kids-habit-tracker
    ports:
      - "3789:80"
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - NODE_ENV=production
